name: CI Lint Job
description: Run linting and formatting checks.
inputs:
  python-version:
    required: true
    description: Python version used for uv environment.
runs:
  using: composite
  steps:
    - uses: jtdub79/PAB_CI_Actions/.github/actions/setup-uv@v1
      with:
        python-version: ${{ inputs.python-version }}
        install-args: --group linting --frozen

    - uses: jtdub79/PAB_CI_Actions/.github/actions/assert-repo-clean@v1

    - name: Ruff Linting (check)
      shell: bash
      run: uv run ruff check . --output-format=github

    - name: Ruff Formatting (check)
      shell: bash
      run: uv run ruff format --check . --output-format=github
