name: CI Lint Job
description: Run linting and formatting checks.
inputs:
  python-version:
    required: true
    description: Python version used for uv environment.
  run-import-linter:
    description: Run import linter
    required: false
    default: "true"
  has-import-health-script:
    description: Run import health script dev-tools/check_import_health.py
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: jtdub79/PAB_CI_Actions/.github/actions/setup-uv@v2
      with:
        python-version: ${{ inputs.python-version }}
        install-args: --no-sources --locked --group linting

    - uses: jtdub79/PAB_CI_Actions/.github/actions/assert-repo-clean@v2

    - name: Ruff Linting (check)
      shell: bash
      run: uv run --frozen --no-sync ruff check . --output-format=github

    - name: Ruff Formatting (check)
      shell: bash
      run: uv run --frozen --no-sync ruff format --check . --output-format=github

    - name: Type Checking (mypy)
      shell: bash
      run: uv run --frozen --no-sync mypy .

    - name: Import Linter
      if: ${{ inputs.run-import-linter == 'true' }}
      shell: bash
      run: uv run --frozen --no-sync import-linter lint

    - name: Import Health Checks
      if: ${{ inputs.has-import-health-script == 'true' }}
      shell: bash
      run: python dev-tools/check_import_health.py