name: Version Gate

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.13"
      tag-or-pr:
        required: true
        type: string


permissions:
  contents: read

jobs:
  version-gate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: jtdub79/PAB_CI_Actions
          ref: v1
          path: PAB_CI_Actions
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run version gate
        run: python PAB_CI_Actions/dev-tools/version_gate.py ${{ inputs.tag-or-pr }}
